# Generated by Django 2.2.2 on 2019-06-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20190609_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='importance',
            new_name='priority',
        ),
    ]
